[package]
name = "walle-q"
version = "0.0.3"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
walle-core = { path = "Walle-core", features = ["impl", "websocket", "http"] }
walle-v11 = { path = "Walle-core/walle-v11" }
rs-qq = { git = "https://github.com/lz1998/rs-qq.git", branch = "master" }
tokio = { version = "1", features = ["full"] }
async-trait = "*"
serde = { version = "1", features = ["derive"] }
serde_yaml = "0.8"
serde_json = "1"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["fmt", "time"] }
time = { version = "0.3", features = ["macros"] }
rmp-serde = "1.0.0"
lazy_static = "1.4"
uuid = "0.8"
clap = { version = "3.0", features = ["derive"] }
cached = "0.34"
bytes = "1.1"
thiserror = "1"
hex = "0.4"
base64 = "0.13"

sled = "0.34"
rusty-leveldb = "0.3"

uri-reader = { git = "https://github.com/abrahum/uri-reader" }

[dev-dependencies]
md5 = "*"

[features]
vendored = ["uri-reader/vendored"]

[profile.release]
lto = true
opt-level = 3
debug = false
debug-assertions = false
overflow-checks = false
strip = true
