[package]
name = "walle-q"
version = "0.1.2"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
walle-core = { version = "0.5.2", features = ["impl", "websocket", "http"] }
walle-v11 = { version = "0.5.0" }
ricq = "0.1.7"
tokio = { version = "1", features = ["full"] }
async-trait = "*"
serde = { version = "1", features = ["derive"] }
serde_yaml = "0.8"
serde_json = "1"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["fmt", "time"] }
tracing-appender = "0.2"
time = { version = "0.3", features = ["macros"] }
rmp-serde = "1.0.0"
uuid = "1.0"
clap = { version = "3.0", features = ["derive"] }
cached = "0.34"
bytes = "1.1"
hex = "0.4"
base64 = "0.13"
sha2 = "0.10"

qrcode = "0.12"
rqrr = "0.5"
image = "0.24"

sled = "0.34"
rusty-leveldb = "0.3"

uri-reader = { git = "https://github.com/abrahum/uri-reader", features = [
    "vendored",
] }

[dev-dependencies]
md5 = "*"

[features]
vendored = ["uri-reader/vendored"]

[profile.release]
lto = true
opt-level = 3
debug = false
debug-assertions = false
overflow-checks = false
strip = true
