[package]
name = "walle-q"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
walle-core = { path = "Walle-core", features = ["impl", "websocket", "http"] }
walle-v11 = { path = "Walle-core/walle-v11" }
rs-qq = { path = "rs-qq/rs-qq" }
tokio = { version = "1", features = ["full"] }
async-trait = "*"
serde = { version = "1", features = ["derive"] }
serde_yaml = "0.8"
serde_json = "1"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["fmt", "local-time"] }
time = { version = "0.3", features = ["macros"] }
sled = "0.34"
rmp-serde = "0.15"
lazy_static = "1.4"
uuid = "0.8"
clap = { version = "3.0", features = ["derive"] }
cached = "0.30"

[dev-dependencies]
md5 = "*"

[profile.release]
lto = true
opt-level = 3
debug = false
debug-assertions = false
overflow-checks = false
strip = true
