name: Release
on:
  push:
    tags:
      - "v*"

jobs:
  release-win:
    runs-on: windows-latest
    strategy:
      matrix:
        include:
          - target: i686-pc-windows-msvc
            name: walle-q-win-i686.exe
          - target: x86_64-pc-windows-msvc
            name: walle-q-win-x86_64.exe

    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: submodle
        run: git submodule update --init
      - name: rust-toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          target: ${{ matrix.target }}
      - name: cargo-build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --target ${{ matrix.target }}
      - name: upload-release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/${{ matrix.target }}/release/walle-q.exe
          asset_name: ${{ matrix.name }}
          tag: ${{ github.ref }}

  release-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - target: aarch64-unknown-linux-gnu
            name: walle-q-linux-aarch64.exe
          - os: ubuntu-latest
            target: i686-unknown-linux-gnu
            name: walle-q-linux-i686.exe
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            name: walle-q-linux-x86_64.exe

    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: submodle
        run: git submodule update --init
      - name: openssl
        run: apt install -y libssl-dev
      - name: rust-toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          target: ${{ matrix.target }}
      - name: cargo-build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --target ${{ matrix.target }}
      - name: upload-release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/${{ matrix.target }}/release/walle-q
          asset_name: ${{ matrix.name }}
          tag: ${{ github.ref }}
